version: '3'

services:
  nginx:
    image: nginx:1.23.4
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
    - "80:80"
    depends_on:
      - app
    container_name: nginx-1.23.4
      
  app:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - database
    container_name: app
  
  database:
    image: postgres:15.2
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=metallica
      - POSTGRES_DB=bandsearcher
      - PGDATA=/var/lib/postgresql/data/some_name/ 
    container_name: database